### ISSUE TITLE
Add LOINC for last exposure to confirmed case

### ISSUE THREAD

**Issue by s-abhyankar** [openhie/covid-ig#11]
http://build.fhir.org/ig/openhie/covid-ig/branches/master/StructureDefinition-WhoCrSurveillanceDataDictionary-definitions.html#WhoCrSurveillanceDataDictionary.exposure.contact.exposureLastDate.

LOINC 95386-9 | Date of most recent contact with confirmed case

**Comment by ElliotSilver** [comment]
commit e5d3de2c13c852ae367af541ef8d5a6567675d27
