### ISSUE TITLE
Add LOINC for location of possible exposure to a case

### ISSUE THREAD

**Issue by s-abhyankar** [openhie/covid-ig#12]
http://build.fhir.org/ig/openhie/covid-ig/branches/master/StructureDefinition-WhoCrSurveillanceDataDictionary-definitions.html#WhoCrSurveillanceDataDictionary.exposure.contactCountry

77984-3 | Country of exposure to illness [Location]

**Comment by ElliotSilver** [comment]
commit e5d3de2c13c852ae367af541ef8d5a6567675d27
