### ISSUE TITLE
Add LOINC for symptomaticDate

### ISSUE THREAD

**Issue by s-abhyankar** [openhie/covid-ig#13]
Would use 65222-2 Date and time of symptom onset for this data element.

http://build.fhir.org/ig/openhie/covid-ig/branches/master/StructureDefinition-WhoCrSurveillanceDataDictionary-definitions.html#WhoCrSurveillanceDataDictionary.outcome.symptomaticDate

**Comment by ElliotSilver** [comment]
commit e5d3de2c13c852ae367af541ef8d5a6567675d27
