### ISSUE TITLE
Add LOINC for outcome status

### ISSUE THREAD

**Issue by s-abhyankar** [openhie/covid-ig#14]
http://build.fhir.org/ig/openhie/covid-ig/branches/master/StructureDefinition-WhoCrSurveillanceDataDictionary-definitions.html#WhoCrSurveillanceDataDictionary.outcome.patientCourse.status

91541-3 | Disease outcome [Type]

**Comment by ElliotSilver** [comment]
commit e5d3de2c13c852ae367af541ef8d5a6567675d27
