### ISSUE TITLE
Copyright attribution

### ISSUE THREAD

**Issue by litlfred** [openhie/covid-ig#15]
For the time being we should probably leave off WHO and put it as OpenHIE.  We should also put it under an appropriate creative common license.

**Comment by ElliotSilver** [comment]
License is now CC-BY-SA-4.0.
I've updated publisher text to be OpenHIE, and to use the ohie.org website.

Note styling is still WHO colours, and WHO/World Health Org is referenced in several locations.

**Comment by ElliotSilver** [comment]
See note above.
