### ISSUE TITLE
CIEL codes for Yes/No/Unknown

### ISSUE THREAD

**Issue by askanter** [openhie/covid-ig#17]
Concept | CIEL Code |  CIEL Description
Yes | 1065 | Yes
No | 1066 | No 
Unknown | 1067 | Unknown

**Comment by ElliotSilver** [comment]
Is there a value I can use for "Partial"? ("Has the Outcome section been submitted? Y/N/Partial")

**Comment by askanter** [comment]
Interesting. I guess the definition of outcome section been submitted doesn't actually ask whether it is complete. There is a CIEL concept for Report Status SCT 308552006 which has as an answer "Partial report status" 162979
