### ISSUE TITLE
CIEL Patient condition value set

### ISSUE THREAD

**Issue by askanter** [openhie/covid-ig#19]
In CIEL, there are two value sets: Overall patient status and a particular patient problem/condition. The overall patient status question is: 159640 Patient health status, with the following answers:

Unknown (1067)
Good (159405)
Fair (159406)
Poor (159407)
Alive (160429)
Dead (160432)
Patient condition resolved (165870)
Patient condition unresolved (165871)

**Comment by ElliotSilver** [comment]
I'm not sure where it came from, but I've got #5622 down as the mapping for other. Is this correct?

The WHO value set is recovered/not recovered/death/unknown/other, which I've got mapped to CIEL as resolved/unresolved/dead/unknown. Should we include mappings for good, fair, poor, alive? If so, what are the WHO equivalents?

**Comment by askanter** [comment]
Unknown (without specifying the unknown) is 5622. I don't think we need to use all the potential options here for the WHO use case. Recovered probably refers to patient condition resolved and not recovered is unresolved. Since we don't know what the actual resolved state is (good, fair, etc.).
