### ISSUE TITLE
CIEL codes for Sex at birth

### ISSUE THREAD

**Issue by askanter** [openhie/covid-ig#20]
Id | 166025 | Sex at birth
Unknown (1067)
Male Gender (1534)
Female gender (1535)

**Comment by ElliotSilver** [comment]
Note that the WHO value set only includes male/female. There is no allowance for unknown or indeterminate.

**Comment by ElliotSilver** [comment]
Note that the WHO value set only includes male/female. There is no allowance for unknown or indeterminate.
