### ISSUE TITLE
CIEL codes for lab results

### ISSUE THREAD

**Issue by askanter** [openhie/covid-ig#22]
INDETERMINATE (1138)
Negative (664)
POSITIVE (703)

**Comment by ElliotSilver** [comment]
In this context, is Indeterminate the same as unknown? 

To me, indeterminate indicates that a test was done but was inconclusive. Unknown indicates that we don't know if a test was done; it was done, we don't know the result; or, that the result was inclusive.

**Comment by askanter** [comment]
Correct. They are not the same. Indeterminate means there was a result, but the result was inconclusive. There is that whole discussions about flavors of unknown :) If you need other values, let me know.

**Comment by ElliotSilver** [comment]
Sorry, I wasn't clear. The WHO value set is positive/negative/unknown. I can easily map positive and negative to CIEL, but I didn't feel that indeterminate was the same as unknown. I will use CIEL 1067 (unknown) instead, and ignore indeterminate above.
