### ISSUE TITLE
Update CIEL relationship types

### ISSUE THREAD

**Issue by askanter** [openhie/covid-ig#23]
Y | is identical to | 1065
N | is identical to | 1066
UNK | is identical to | 1067

a	is identical to	1734
mo	is identical to	1074
d	is identical to	1072

RECOVERED (Recovered/Healthy) | is identical to | 165870
NOTRECOVERED | is identical to | 165871
DEATH | is identical to | 160432
UNKNOWN | is identical to | 1067
OTHER | is identical to | 5622

male | is identical to | 1534 |  
female | is identical to | 1535

Not sure what to do with these. The concept is "first trimester" but the term is "first". The mapped CIEL concepts are all trimester concepts and would be identical to.
first | is related to | 1721
second | is related to | 1722
third | is related to | 1723

CASE_CONTACT (Contact of a case) | is identical to | 162633
SEEKING_HC (Ill Seeking Healthcare due to suspicion of COVID-19) | is identical to | 165650
POE_DETECTION (Detected at point of entry) | is identical to | 165651
REPATRIATION | is identical to | 165652
SURVEILLANCE (Routine respiratory disease surveillance systems (e.g. influenza)) | is identical to | 165653
UNKNOWN | is identical to | 1067

Y is missing
partial | is identical to | 162979
N | is identical to | 1066

POS | is identical to | 703 
NEG | is identical to | 664

**Comment by ElliotSilver** [comment]
For trimester, the code system I created is specifically for trimester, so "first" is not ambiguous (cannot be confused with first born, first finger, etc.) I'm using "identical" for the mapping.

For "previously submitted" (Y/N/partial), I've corrected the missing Y.

Done.
