### ISSUE TITLE
Logical model make contact setting a codeable concept

### ISSUE THREAD

**Issue by ElliotSilver** [openhie/covid-ig#37]
Add an example vocabulary

**Comment by ElliotSilver** [comment]
Updated logical model and questionnaire.
Need to populate value set with typical locations.

If we can't figure out a decent ValueSet, we should revert back to #string type.

**Comment by askanter** [comment]
Since this does not specify hospital setting, it could be ANY setting and that might be hard to document with the Environment hierarchy in SNOMED.
