### ISSUE TITLE
Logical Model Change contact exposure to period

### ISSUE THREAD

**Issue by ElliotSilver** [openhie/covid-ig#39]

**Comment by askanter** [comment]
Exposure has a start data and end date. What is this issue asking? Should there be an array of exposure periods?

**Comment by ElliotSilver** [comment]
In the current logical model, there are separate first and last dates for contact exposure. These values are stored in separate elements of type date. The proposal is to change to a single element of type period, which has begin and end sub-elements. Essentially the same data is carried in both representations, but the use of the period data type conveys the relationship between the two values.

I don't think making the contact begin/end elements or contact period element repeat is necessary for the purposes of this form. In cases of multiple exposure with the same contact, I would suggest recording the beginning of the first exposure and the end of the last; or, alternatively, create multiple contact entries each for the same person.

I'll mark this for discussion.

**Comment by ElliotSilver** [comment]
Group: allow period/setting to repeat per contact.
