### ISSUE TITLE
Duplicate variables under clinicalStatus and outcome

### ISSUE THREAD

**Issue by s-abhyankar** [openhie/covid-ig#5]
The "clinicalStatus" and "outcome" data element groups both include patientCourse variables. Five of the variables listed under patientCourse are the same in both places. Not sure if this is intentional or not.
http://build.fhir.org/ig/openhie/covid-ig/branches/master/StructureDefinition-WhoCrSurveillanceDataDictionary-mappings.html

If it's intentional and the meanings are meant to be exactly the same, would use the same LOINCs.

**Comment by ElliotSilver** [comment]
My interpretation of the WHO spreadsheet is that the clinicalStatus elements are filled in when the report is first filed (within 48 hours of diagnosis); the outcome elements are filled in once the case is resolved.

My interpretation of the elements would be something like "initially admitted to hospital" and "ever admitted to hospital during the course of this case". @s-abhyankar, does that impact which codes are used?

**Comment by askanter** [comment]
I think it is common for there to be unnecessary variation in variables. I really wonder whether this was just a replication of the original data versus actually a different definition. I would think in this case the admission (and date) is the same variable.

**Comment by s-abhyankar** [comment]
@ElliotSilver ,  "initially admitted to hospital" and "ever admitted to hospital during the course of this case" would definitely have different codes because they have two different meanings.
However, looking at the case report form again, I agree with Andy that the variables are meant to report the same thing in both places - whether the patient was admitted to the hospital and if yes, the date of admission (date of first admission if admitted more than once).

I would use the same LOINCs for these elements in the different instances (in the FHIR build the LOINCs are filled in for one instance and say "TODO" for the second.

**Comment by s-abhyankar** [comment]
@ElliotSilver  I was going to re-assign to you but don't seem to have that option.

**Comment by ElliotSilver** [comment]
On further review, decided that these are intentionally the the same questions. Use the same code.
