### ISSUE TITLE
Change first/last date of contact to date type

### ISSUE THREAD

**Issue by ElliotSilver** [openhie/covid-ig#55]

**Comment by askanter** [comment]
Should this be date/time?

**Comment by ElliotSilver** [comment]
I'm not sure that it is needed. 

First, the WHO data dictionary doesn't specify datetime, so we'd be collecting more detail than they are asking for, unless we ask WHO to change. 

Second, I think the use case is to broadly identify persons of interest/potential sources. I suspect too many matches is safer than too few. It seems risky to eliminate a potential contact because they left an area at (by their statement) 1:30, and the patient didn't arrive (by their statement) until 2:00. I'd rather know they were both in the same location on the 25th, and then can follow-up with each person to probe for details.

The element may also be focused on figuring out incubation period. I'm not sure if hours are needed for that, or if days are sufficient.

However lets bring it up to the group.

**Comment by ElliotSilver** [comment]
Group consensus: move to datetime. (and then potentially to period)

**Comment by ElliotSilver** [comment]
Updated both questionnaire and logical model to dateTime. New issue raised for period (#67)

Done.
