### ISSUE TITLE
"admin0" variable name is used twice, with 2 different meanings

### ISSUE THREAD

**Issue by s-abhyankar** [openhie/covid-ig#7]
http://build.fhir.org/ig/openhie/covid-ig/branches/master/StructureDefinition-WhoCrSurveillanceDataDictionary-mappings.html

admin0 is listed under "identified" and "residence" but under "identified" means country where the case was diagnosed and under "residence" means Country where the case usually resides.

77983-5 is correct for residence/admin0.

**Comment by ElliotSilver** [comment]
My interpretation of "admin0" is that is WHO-speak for "country", while "admin1" is "state/province." Thus the two variables are the country where the case was identified, and the country where the case resides. The names (patientInfo.*residence* and patientInfo.*identified*) should make it clear why we are recording the admin0 info.

I propose to close this with no change. Please re-open if you disagree.
