### ISSUE TITLE
New LOINC codes for WHO data elements

### ISSUE THREAD

**Issue by s-abhyankar** [openhie/covid-ig#73]
@ElliotSilver , attached is a spreadsheet with all of the new LOINC codes, except for the couple that have outstanding questions.
The variable name in the WHO data dictionary is in the "Submitted Local Code" column (column U) - you should be able to match everything up based on that.

Please let me know if you spot any errors as you load these. Thank you!
[20201117 LOINC CompletedTermReport_ID 5723.xlsx](https://github.com/openhie/covid-ig/files/5555990/20201117.LOINC.CompletedTermReport_ID.5723.xlsx)

**Comment by s-abhyankar** [comment]
@ElliotSilver , here are some additional mappings to existing LOINCs. 

FHIR variable | WHO data dictionary variable | LOINC code | Long common name
1. pregnant | Comcond_preg | 82810-3 | Pregnancy status --> I would recommend using this code for pregnancy and not lumping it with the other comorbidities since it's a little different from the others and the trimester question hinges on it.
2. setting | expo_case_setting_detail | 81267-7 | Setting of exposure to illness
3. city | patinfo_occuhcw_city | 80431-0 | Employer city
4. country | patinfo_occuhcw_country | 80437-7 | Employer country [Location]
5. facilityName | patinfo_occuhcw_name | 76696-4 | Name [Identifier] Facility
6. date | report_date | 77995-9 | Date of first report to public health department
7. testReasonOther | report_test_reason_other | 67098-4 | Reason for test or procedure

Between what's already mapped, the new codes I posted last week, and these, I think we're covering everything except the 3 concepts with outstanding questions:
1. Discharge/death/release from isolation date; 
2. Date of first lab test; 
3. Symptoms at time of specimen collection)

**Comment by s-abhyankar** [comment]
Sorry - one more:

immunodeficiency | Comcond_immuno | 96381-9 | Immune status

**Comment by ElliotSilver** [comment]
Updated. I noticed some missing values though, I've filed #78 to track others that we're missing.
