### ISSUE TITLE
Further LOINC codes

### ISSUE THREAD

**Issue by ElliotSilver** [openhie/covid-ig#78]
@s-abhyankar - As I was reviewing other LOINC changes I noticed we're potentially missing several codes.

For the following, I'm missing codes for the answers. (I suspect that these aren't covered by LOINC; if that can be confirmed, I'll remove the mapping tables.)
- Units of time? (day, month, year)
- Reason for testing? (case contact, seeking healthcare, point of entry, repatriation, surveillance, unknown)
- Patient outcome? (recovered, not recovered, death, unknown, other)
- Pregnancy trimester? (first, second, third)
- Patient sex at birth (m, f)
- Test result (pos, neg, unknown)
- Report previously submitted (yes, no, partial)
- Also generic yes, no, unknown

I see in the spreadsheet included in #73 that LA33-6, LA32-8 cover yes and no, and there are also LA values for pos and neg. What is the code system for these values?

We have codes for some of the co-morbidities (pregnancy, postpartum, immunodeficiency) but are missing others:
- cardiovascular disease
- diabetes
- hepatopathy
- renopathy
- chronic neurological or neuromuscular disease
- malignancy
- chronic lung disease

Also missing (some of these are ones you listed on #73):
- date of first laboratory confirmation
- is the patient asymptomatic
- did an asymptomatic patient develop symptoms
- report outcome previously submitted
- date of release from isolation/hospital.

Thanks.

**Comment by s-abhyankar** [comment]
@ElliotSilver , the answers and answer codes should come from ICD and/or SNOMED CT.

LOINC contains Answer lists attached to nominal and ordinal codes, and these lists contain answer strings and corresponding LA codes (for which the code system is LOINC), but we encourage users to use codes from other standard terminologies for qualitative answers where possible.

Units of measure should be specified using UCUM.

We decided on the last call that we wouldn't create a LOINC code for "report outcome previously submitted", and I believe the other 4 need clarification from WHO (the two related to symptoms would have the same LOINC).

**Comment by ElliotSilver** [comment]
Sounds good. Closing with no changes.
