### ISSUE TITLE
comorbidities LOINC code

### ISSUE THREAD

**Issue by s-abhyankar** [openhie/covid-ig#8]
LOINC 75618-9 is used to report the specific comorbid condition(s), not whether or not a comorbid condition is present. There is no LOINC code for comorbid condition presence/absent.

**Comment by s-abhyankar** [comment]
Looking at the case report form, 75618-9 would be appropriate for the "If yes, please check all that apply" where the results for this observation would be the appropriate SNOMED codes for each condition. It could also be used to report "No comorbidities", but should not be used for a Yes/No answer list.

**Comment by ElliotSilver** [comment]
This looks to have been applied or no change was needed.
